# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{king_hmac}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Georg Leciejewski"]
  s.date = %q{2010-04-10}
  s.description = %q{A Ruby Gem for authenticating HTTP requests using a HMAC}
  s.email = %q{gl@salesking.eu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/king_hmac.rb",
     "lib/king_hmac/auth.rb",
     "lib/king_hmac/cannonical_string.rb",
     "lib/king_hmac/headers.rb",
     "lib/king_hmac/rack/middleware.rb",
     "lib/king_hmac/rails/active_resource.rb",
     "lib/king_hmac/rails/controller.rb",
     "spec/fixtures/credentials.yml",
     "spec/king_hmac/king_hmac_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/salesking/king_hmac}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby Gem for authenticating HTTP requests using a HMAC}
  s.test_files = [
    "spec/king_hmac/king_hmac_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

